name: Minimum Reviewers Check
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Check Reviewers
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            if (pullRequest.requested_reviewers.length < 2) {
              core.setFailed('At least one reviewer is required');
            }
